### ISSUE TITLE
As a designer, i want to research how to make the Safe zone evoke ambient tranquility  in the player 

### ISSUE THREAD

**Issue by GPJFlorge** [UoSGamesGroups/first-semester-group-1#1]
Do this by making the station feel more homely. Adding person effects, warmer colours

**Comment by benattebery** [comment]
Committed 2 hours to this piece and it is now up on here.
![homey](https://cloud.githubusercontent.com/assets/22661054/19706773/a6a6128a-9b0b-11e6-83ce-0f16bd278d5e.png)
