### ISSUE TITLE
1: As a designer, I want to design a background

### ISSUE THREAD

**Issue by GPJFlorge** [UoSGamesGroups/first-semester-group-1#10]
Using the research and the concepts you came up with last week, design a 1920x1080 background image using Photoshop layers that can be used in the section of the game before the Main Character reaches the safe area. It should include a sky background, ground and assets in the foreground.
This can use...
- The sand dunes 
- The trees
- The sky
  ...that you conceptualised last week

**Comment by benattebery** [comment]
I have completed the background and will upload tree sprites to be added to the middle ground just behind the foreground. We need to decide what we want for the ground. Sprite blocks or a solid foreground. I am leaning toward sprites to be added into the game that are interact-able. Took me approx. 3 hours to complete.
