### ISSUE TITLE
Continue working on enemy ai

### ISSUE THREAD

**Issue by GPJFlorge** [UoSGamesGroups/first-semester-group-1#26]

**Comment by AKegge** [comment]
Unity no longer crashes when the player is killed, enemies still arn't moving despite using the same code that worked before. I'm going to ask Cris about this on monday.

Not sure how long I worked on this as I worked in lots of short burts (around 5-10 minutes) over the course of 5 hours.

**Comment by AKegge** [comment]
Didn't get the chance to ask Chris. Spent another hour checking the code today, including running it step by step. It looks like it should be working but when run in Unity the enemies still don't move, probably something obvious that I'm missing.
