### ISSUE TITLE
As a designer, I was to design some concepts for the outer environment 

### ISSUE THREAD

**Issue by GPJFlorge** [UoSGamesGroups/first-semester-group-1#3]
Using the research, Start to conceptualise the appearance of the outer environment

**Comment by benattebery** [comment]
Committed 2 hours to this part and it is now up on here.
![desert](https://cloud.githubusercontent.com/assets/22661054/19706732/6b18c2ee-9b0b-11e6-9a73-29c9820de3f1.png)
