### ISSUE TITLE
As a designer I want design a rough layout for a level

### ISSUE THREAD

**Issue by GPJFlorge** [UoSGamesGroups/first-semester-group-1#48]
Consider the enemy's and the kind of puzzles involved. Doesn't need to be finalised version, can just be ideas/concepts.

Estimated: 3h

**Comment by GPJFlorge** [comment]
Should revolve around ways to avoid an enemy

**Comment by benattebery** [comment]
Great thank you...
Ill have this in tonight for you

Ben


________________________________

**Comment by benattebery** [comment]
Added a simple level sketch to give the player an introduction to the game.
